### PR TITLE
Update social networks

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #46 

Added social networks mentioned in the issue.
Changed class `social-media-icon-<?php echo esc_attr($instance['size']) ?>` to `<?php echo esc_attr($instance['size']) ?>-social-media-icon` since it was conflicting with medium.com's icon.
@Misplon let me know if I should change the colors of any icons or maybe rearrange certain icons. Thanks.

### CODE REVIEW

**Comment by gregpriday** [comment]
I'd prefer to keep the `social-media-icon` prefixing - so how about we use something like `social-media-icon-size-medium`?

Another enhancement we should make, especially with the CSS for the widget getting fairly large, is moving all its CSS into a separate file. If someone isn't using the widget, it's a lot of unnecessary CSS to add to their stylesheet.

There is a way to detect if a widget is on a page (this is what the sidebars emulator in Page Builder simulates) - although I can't quite remember how it works. This is the mechanism we should use to make sure the widget's CSS is loaded in the head.

**Comment by adiraomj** [comment]
Thanks for the feedback. I'll get on it.

**Comment by adiraomj** [comment]
All done.

**Comment by Misplon** [comment]
@adiraomj The output and code all look awesome. Lovely work! @gregpriday You happy?

**Comment by gregpriday** [comment]
Everything looks good to me!

**Pull request merged**
