### PR TITLE
Blog update

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancements #150, #157, #158 

Added setting to enable read more button for excerpt's
Added columns setting for circle icon and grid loop archives
Applied read more setting to circle and grid archive loops

@Misplon please have a look at the responsive state of the loops with different column counts and let me know if any changes are needed. Thanks.

### CODE REVIEW

**Comment by Misplon** [comment]
Awesome! Thanks for the push Adi, appreciate it. Could you have a look at the conflicts when you have a moment?

**Comment by adiraomj** [comment]
Sorted it out

**Comment by Misplon** [comment]
Really nice work dude.

Do you think we should rather add the same Continue Reading > link for the grid as we're using the Circle Icon layout? So no button, just a text link with the arrow. I think it might work better given the lack of space.

**Comment by adiraomj** [comment]
Made change.

**Pull request merged**
