### PR TITLE
Widgets styling

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #37 

Updated submodules
Added some gap between list items.
Made elements in tag cloud have same font size.

@Misplon could you have a look. Are there any suggestions you could give to improve it further? Or anything that I should undo?  Thanks.

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks for the effort @adiraomj. Quite tough to comment on a commit like this because design is so subjective. The below is of course my opinion.

**Search:** The updated search widget looks great.

**Tag Cloud:** Are you certain it's better to remove the tag sizing differences? It feels as though that takes away a bit of the cloud usability.

**Category Drop-Down:** I think the categories drop down would look better at `1em`.

categories

**List Styling:** I think the `li ` bottom spacing is too much and would look better with list items closer together, perhaps `7` or `8px`.

list-styling

Thanks :) Let me know your thoughts.

**Comment by Misplon** [comment]
@adiraomj Do we also need to investigate WooCommerce widget styling?

**Comment by adiraomj** [comment]
@Misplon I was in 2 minds about the tag cloud. I'll revert the change I made. I'll have a look at all the WooCommerce widgets as well. :)

**Comment by adiraomj** [comment]
For the product search widget, do you feel we make it look similar to the default search widget? i.e, remove the button and make the fields corners curved.

**Pull request merged**
