### PR TITLE
Small modifications to improve mobile UX

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #26 

removed link around comment metadata
increased size of comment form's submit button 

https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fsotest.wpengine.com%2F%3Fp%3D88

Note: this may need review from time to time as the theme evolves :(

### CODE REVIEW

**Comment by adiraomj** [comment]
@Misplon please have a look now :)

**Comment by Misplon** [comment]
@adiraomj Thanks, man. What do you think about dropping the buttons down to `14px`? We'll also need to `float: none` these buttons at around `680px` to prevent overlap.

buttons

**Comment by Misplon** [comment]
Otherwise looking nice and usable.

**Comment by adiraomj** [comment]
Dropping it to 14px should be fine I guess. :)

**Comment by adiraomj** [comment]
Done

**Pull request merged**
