### PR TITLE
Linked comments section elements to existing color settings

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #128 

Linked comment meta links to **Content Color**.
Linked other comment elements to **Content Heading Color**.

Any suggestions/changes?

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks :)

Can we expand the scope of the link color settings to include the following:

`logged-in-as`

logged-in

Finally, do we have any settings that cover these borders?

```
#comments-title, #reply-title {
    border-bottom: 2px solid #555555;
}

#reply-title {
    border-bottom: 2px solid #555555;
}
```

**Comment by adiraomj** [comment]
@Misplon for the `logged-in-as` links, I have linked it to the Content link color and Content link hover color.

I don't see any setting we can directly link the `border-bottom` to. Any ideas?

**Comment by Misplon** [comment]
Thanks @adiraomj sounds good re: links.

The border-bottom is `#555` and the content heading color is `#444`. Want to use Content Heading color? It'll only have an impact after it has been changed by the user and is fairly close.

**Comment by adiraomj** [comment]
cool.. I'll do that :)

**Comment by Misplon** [comment]
Thanks @adiraomj. I've been a bit slow the last 10 days as I was away with less than awesome interwebs. Back now :) Sorry for missing this, can we also look into:

```
#comments .commentlist article .comment-author {
color: #474747;

#comments .commentlist article .comment-author .author-comment-label {
background-color: #eee;
```

Keeping in mind that `#474747` is the color used for the second selector over the background `#eee`.

Should we link `#comments .commentlist article .comment-author` to **Content Heading Color**? For the author indicator background I'm not sure. We could leave it out for now or use a lighten function on an existing color.

**Comment by adiraomj** [comment]
@Misplon The `#comments .commentlist article .comment-author` is already linked to  **Content Heading Color**. However that is only when it is a link. I'll fix this.

I feel we can leave out the `.author-comment-label` for now. The color `#eee` goes well as a background for most colors. We can maybe look into it if we get user requests for it.

**Pull request merged**
