### PR TITLE
WP unit test

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #81.

Added vertical align to gallery images
Added word-wrap to .site-content
Styled `<pre>` and `<code>`
Changed post thumbnail to max-width to accommodate vertical images
Removed left margin for first level ordered lists

@Misplon and @gregpriday let me know if I have to undo any changes incase it affects existing users. Thanks.

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj Are you sure about using `break-word`? This has caused problems in the past when accidentally used in one of the updates. It forces words to break at points where they normally wouldn't break so it can make content look odd. It's appropriate for `pre` or `code` but isn't usually ideal for normal text content as far as I understand. Can you perhaps let me know the issue you were trying to solve, perhaps we can take another look at it.

**Comment by Misplon** [comment]
@adiraomj should we consider removing `max-width: 100%` and `height: auto` here:

https://github.com/siteorigin/vantage/blob/develop/style.css#L1127-L1132

And instead adding those declarations to the img tag as _s does:

https://github.com/Automattic/_s/blob/master/style.css#L404-L406

It looks like we're missing adding those declarations to `img`, unless I overlooked a rule?

**Comment by adiraomj** [comment]
Good idea @Misplon. I'll do that. Should make the stylesheet a little lighter. 👍

**Comment by adiraomj** [comment]
This is the example post:

vantage-word-break

I noticed that earlier `word-break` was applied to the `body`. I have now applied it to `.site-content` like what has been done in [TwentySixteen](https://github.com/WordPress/twentysixteen/blob/master/style.css#L1518-L1520).

Could this have been the issue? I wonder.

**Comment by Misplon** [comment]
You're right. Perfect. Nicely done!

**Pull request merged**
