### PR TITLE
Button styling

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #130

Added a new **Buttons** Section to **Theme Design**.
Added and implemented _Button Background Color_, _Button Color_, _Button Border Color_, _Remove Button Text Shadow_ and _Remove Button Shadow_ settings.

@Misplon please let me know if I have missed any buttons. Thanks

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj Thanks dude. Please, can we change the checkboxes to default enabled and change the labels to:

**Button Text Shadow**
**Button Shadow**

Hopefully, you're cool with that change. I think we're ok to remove the action and leave the checkbox to represent the action.

**Comment by Misplon** [comment]
WooCommerce category and single pages are looking good but we might need to check out the checkout button colors.

**Apply Coupon**
apply-coupon

**Update Cart**
update-cart

**Proceed to Checkout**
proceed-to-checkout

**Place Order**
place-order

For the blue buttons, do you want to consider adding a WooCommerce dependent button section? Ideally we'd leave WooCommerce button styling up to the WooCommerce colors plugin but since we're already adding blue styling for certain buttons, we need to have a way of changing those somehow.

**Comment by adiraomj** [comment]
@Misplon for the woocommerce **Proceed to Checkout** and **Place Order** buttons we can add a new field **WooCommerce Secondary Button Background**. Sound good?

**Comment by adiraomj** [comment]
@Misplon I was just having a look at the buttons. Do you think we need to add settings for the hover state?

**Comment by Misplon** [comment]
@adiraomj Is this branch ready to be checked again or in progress? Thanks :)

**Comment by adiraomj** [comment]
In progress. A little bit more to do

**Comment by adiraomj** [comment]
Added settings for WooCommerce checkout and cart buttons.
Added check to remove WooCommerce settings if plugin is not active.

@Misplon the PR is ready. Please have a look.

**Comment by Misplon** [comment]
Thanks @adiraomj. Controls are looking great.

I think we need to look at the wording of the WooCommerce button labels, even though they are quite long already. If we name them as is, it implies all WooCommerce buttons but we're only changing the Checkout and and Place Order Buttons.

Can we perhaps try adding a sub-heading for WooCommerce in the Buttons section? Is that perhaps possible using a field?

**WooCommerce:**

Checkout Button Background Color
Checkout Button Color
Checkout Button Border Color

**Comment by adiraomj** [comment]
@Misplon after discussing with Greg, it was decided that a sub-heading field will be added. Would you like me to update the labels of the existing fields for now?

**Comment by Misplon** [comment]
This is great. I think we could potentially merge now and add the sub-heading once the settings field is available. Even without the sub-heading it makes sense. You cool with that plan?

**Comment by adiraomj** [comment]
Good Plan. I'll fix merge conflicts tonight.

**Comment by Misplon** [comment]
Sweet.

**Comment by adiraomj** [comment]
@Misplon Please have a look. I have added support for infinite scroll button. :)

**Pull request merged**
