### PR TITLE
Social widget update

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #10 

Added email option. Checked if input was email-id and prepended with `mailto:` if necessary.
Added phone option. Checked if input was not a url and prepended with `tel:` if necessary.
Moved RSS link above email and phone options.
Checked if skype link has `skype:` or `callto:` and added if not present.

### CODE REVIEW

**Comment by gregpriday** [comment]
Code all looks good to me. @Misplon - after a quick review of functionality, this is ready to merge.

**Comment by Misplon** [comment]
@gregpriday Super, thanks, will test shortly.

**Comment by Misplon** [comment]
@adiraomj Thanks dude. The phone number field appears to be appending `tel` even with a URL, can you perhaps look into that for us?

**Comment by Misplon** [comment]
@adiraomj the Skype link auto prepend with `skype` or `callto` doesn't appear to be working for me, can you see if it's still working on your side? Thanks :)

**Comment by adiraomj** [comment]
@Misplon let me have a look

**Comment by adiraomj** [comment]
@Misplon I have corrected the problem. Everything should work fine. Let me know.

**Pull request merged**
