### PR TITLE
Icon circle widget colors

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #15 and #14 

Changed the existing color field to color picker.
Added color fields for title and text

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj Thanks :)

I'm seeing the new colour fields but am just seeing a text field at the moment, no colour picker. Any ideas?

**Comment by adiraomj** [comment]
Hmmm. Not sure what's wrong. I'm getting something like
circle-widget-color

Maybe a plugin you have installed is conflicting with it. Could you maybe have a look and let me know if that's the problem?

@gregpriday could you please have a look at the code and see if I am going about things the right way. Thanks. :)

**Comment by Misplon** [comment]
@adiraomj Sorry, I'll screenshot next time. I'm testing in Page Builder, have you taken a look in PB? Thanks :)

**Comment by adiraomj** [comment]
@Misplon please check it now. Should be fixed. Thanks for pointing out the PB compatibility. :)

**Comment by Misplon** [comment]
@adiraomj I'm still seeing the following in PB:

circle-icon-pb

I have Vantage branch #34 checked out. Is there anything that might be different about my setup?

**Comment by adiraomj** [comment]
It seems to be working fine for me.

circlewidget-pb

Not sure why it isn't working for you. Any ideas @gregpriday ?

**Comment by Misplon** [comment]
@adiraomj not sure why I'm not seeing the final result. @gregpriday Can you please, confirm for us. Thanks.

**Comment by Misplon** [comment]
@adiraomj Apologies for the hassle. Had a good look around at caching the other day, turned off OPcache and it seems to have helped. 

Please, could you move the following settings onto their own line under their labels:

Title Color
Text Color
Icon Background Color
Icon Position
Icon Size

Thanks :)

**Comment by adiraomj** [comment]
Added line breaks to above mentioned fields.

**Comment by Misplon** [comment]
Sorry @adiraomj can we lastly put Icon drop-down on its own line, then we're all sorted. Apologies for missing that.

**Comment by adiraomj** [comment]
Done :)

**Pull request merged**
