### PR TITLE
fixed issue with menu home icon

### PR DESCRIPTION
**Pull request by adiraomj**
Fixed issue #92

### CODE REVIEW

**Comment by adiraomj** [comment]
Yes it does. Works great. Can you please confirm @gregpriday? Thanks

**Comment by Misplon** [comment]
@adiraomj Are you testing with a Page or a Custom Link? With a Custom Link it works but with a Page it doesn't seem to work.

**Comment by adiraomj** [comment]
Hmm.. One moment. I'll check again.

**Comment by adiraomj** [comment]
@Misplon please test it now

**Pull request merged**
