### PR TITLE
Added site description setting

### LINKED ISSUE #294: Site Description: Add an option to display the site description/tagline
Add a default disabled option to display the site description/tagline below the logo.

### PR DESCRIPTION
**Pull request by Misplon**
Resolves #294. Adds a default disabled setting to add the site description.

Please, test both masthead layouts. Responsive views and related size and text color settings.

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
Looks good - I'm not seeing any responsive issues.

I do have an issue with the fact we're setting a hard color as there are definitely situations when #e2e2e2 won't be a useable color. Rather than introducing a new setting (which isn't ideal), we might be able to get away with using the same color as the Site Title.

On a semi-related note, it would be a good idea to introduce vertical alignment for the contents of .logo when **Display site title alongside logo** is enabled as it'll look neater overall.

Before:


After:

**Comment by Misplon** [comment]
Thanks for the feedback. 

The site tagline is linked to the Header Text Color and Header Text Size settings.

**Comment by Misplon** [comment]
Vertical alignment changes added as per feedback.

**Comment by AlexGStapleton** [comment]
I can't seem to get those two settings to affect the site description. Can you please double check that the color and font size is changeable for you?

**Comment by Misplon** [comment]
Sorry about that, they got lost in a change that I rolled back locally.

**Comment by AlexGStapleton** [comment]
No worries mate. 

Vertical Alignment looks good! 👍

**Comment by AlexGStapleton** [comment]
Customizer changes work upon saving but unlike the Header Text, they aren't updating automatically.

**Comment by Misplon** [comment]
They are for me. Caching maybe?

**Comment by AlexGStapleton** [comment]
Whoops! Yeah, you're right, it was caching (although I'm not too sure what). Everything looks good. :)

**Comment by Misplon** [comment]
Super, thanks.

**Pull request merged**
