### PR TITLE
Added font setting for main navigation

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #124

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj Thanks dude. Should we look at applying the font family setting to `.mobile-nav-frame .title h3` ? Or perhaps use the Heading font setting?

**Comment by adiraomj** [comment]
@Misplon I feel we can link `.mobile-nav-frame .title h3` to the menu font. Seems more appropriate.

**Comment by Misplon** [comment]
Super, let's do that.

**Comment by adiraomj** [comment]
@Misplon added mobile menu heading to the font setting.

**Pull request merged**
