### PR TITLE
Changed menu collapse setting to range.

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #52

### CODE REVIEW

**Comment by adiraomj** [comment]
@Misplon better?

**Comment by Misplon** [comment]
@adiraomj Nicely done!

**Comment by Misplon** [comment]
@adiraomj Should we remove this line for now?

https://github.com/siteorigin/vantage/pull/74/files#diff-242ac734dbaf32c59cd060dfa1e7e1beL105

**Comment by adiraomj** [comment]
@Misplon I guess we can. It does not seem to be functional anyway.

**Comment by Misplon** [comment]
@adiraomj That's my thought. Let's take it out and put it back in when functional.

**Comment by adiraomj** [comment]
Done

**Pull request merged**
