### PR TITLE
Footer menu styling

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented issue #114

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj What do you think about using padding rather so that the lines all start at the same point and only the text indentation differs?

**Comment by Misplon** [comment]
@adiraomj A quick reminder here for when you have a moment. Let's keep the divider lines standard width and just indent the link/menu item to show hierarchy. Thanks dude :)

**Comment by adiraomj** [comment]
@Misplon using css to add padding to links will only work for the first level submenu.

I took the js approach. I counted the number of `.sub-menu`'s above each link. and then applied padding based on that value.

**Comment by Misplon** [comment]
Thanks @adiraomj.

Do we really need JS for this? Each new sub-menu item is in a new `ul` within the initial `ul` so should be able to do this with CSS only just as you would style the main menu drop-downs.

**Comment by adiraomj** [comment]
The tricky bit would be getting the full width line between each element. I'll try to see if I can do the same with CSS.

**Comment by Misplon** [comment]
Thanks @adiraomj let me know how it goes.

**Comment by Misplon** [comment]
@adiraomj When you're free can you perhaps take another look at this guy? Thanks :)

**Comment by adiraomj** [comment]
@Misplon I tried a few things with CSS, but didn't seem to work. Maybe we can merge this now. If I come across or think of something for this I'll send another PR. Sound good?

**Comment by Misplon** [comment]
@adiraomj No problem. Greg was pretty keen on us resolving this without JS when I chatted to him about it. We have a lot on the go at the moment. Please, leave this for the moment and I'll check it out this weekend if I get a moment, otherwise Monday. Just need to get some basic docs done for SiteOrigin Premium. Happy to have you move onto the other issues we have open that are more complex.

**Comment by Misplon** [comment]
@adiraomj You're right. I took a look at the various methods on offer and they are all very static in nature. We'd basically need to specify a padding for each level of the tree. Happy with the JS approach.

**Pull request merged**
