### PR TITLE
Slider update

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #238 
Added smart slider integration.

@Misplon please test and let me know if I missed anything. Thanks

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj Is the conditional meta box working correctly for you? At the moment, I still see the the MetaSlider meta box, even if the plugin is deactivated and or deleted.

**Comment by Misplon** [comment]
Sorry @adiraomj I merged in the incorrect order. Please, can you fix this conflict and also in inc/smartslider.php, please add:

`siteorigin`

as our affiliate ID.

Thanks :)

**Comment by AlexGStapleton** [comment]
I've run a few tests and everything looks good. I did notice one issue, it's not possible to remove the home page slider by using only the Smart Sider box (none doesn't work). This suggests that [this line](https://github.com/siteorigin/vantage/pull/239/files#diff-52bd3de5261d6c59ba1bc9776f097e00R51) isn't working.

If you set a Smart Slider and a Meta Slider for a page, it'll work without issue. If you then deactivate Smart Slider 3, Meta Slider won't be able to be full width stretch. This is only an issue because chances are people will try Smart Slider 3 and may revert to their previous Meta Sider setup without setting page Smart Slider box to none.

**Comment by Misplon** [comment]
Awesome work.

@adiraomj Any chance you could look into these two small issues for us?

**Comment by adiraomj** [comment]
For the issue:
> I've run a few tests and everything looks good. I did notice one issue, it's not possible to remove the home page slider by using only the Smart Sider box (none doesn't work). This suggests that this line isn't working.

The logic is set such that both metaslider and smart slider have to be set to `none`. This is to account for users that use both sliders on different pages. Please correct me if I am wrong. :)

Fixed the metaslider stretch issue after smart slider deactivation. Test. Thanks.

**Comment by AlexGStapleton** [comment]
Sorry, by home page slider I meant the default demo slider on the home page.

**Comment by Misplon** [comment]
Sorry about the delays here @adiraomj and @AlexGStapleton. I'm offline most of Monday but will see this through this week.

**Comment by Misplon** [comment]
* With MetaSlider and SmartSlider deactivated, If I reset the options table, there is no default home page demo slider. There is if I reset the options table in the current `develop` branch. If I activate MetaSlider the default slider appears.

* Alex point 01: Yes, I see that only the MetaSlider setting "none" will deactivate the theme demo slider. I'm ok with this. @AlexGStapleton Reckon we can leave this one?

* Alex point 02: Sweet, stretch is fixed. However, if I set both a SmartSlider and MetaSlider on a page, only the SmartSlider displays. @adiraomj Is this correct or should both sliders display?

Thanks for the effort @adiraomj and Alex for the testing, much appreciated guys!

**Comment by AlexGStapleton** [comment]
1. Yeah, that's fine mate. Doubt many will notice, and it's easily fixed.

**Comment by Misplon** [comment]
@AlexGStapleton Can you perhaps confirm the first and last point above so I know we're both seeing them? Thanks!

**Comment by AlexGStapleton** [comment]
I can confirm I'm able to replicate both of those.

I've attempted to fix both of these issues and I ended up with the following PHP:

```
function vantage_render_slider() {

	if ( is_front_page() && ( ! in_array( siteorigin_setting( 'home_slider' ), array( '', 'none' ) ) || ! in_array( siteorigin_setting( 'home_smartslider' ), array( '', 'none' ) ) ) ) {
		$settings_slider = siteorigin_setting( 'home_slider' );
		$slider_stretch = siteorigin_setting( 'home_slider_stretch' );
		$smartslider = siteorigin_setting( 'home_smartslider' );

		// Check if we should show demo slider or not.
		if ( ( $settings_slider == 'demo' || empty( $settings_slider ) ) && empty( $smartslider ) ) {
			$slider = 'demo';
		} else {
			// Don't show demo slider, show normal sliders
			if ( ! empty( $settings_slider ) && defined( 'METASLIDER_VERSION' ) ) {
				$slider = $settings_slider;
			}

			if ( ! empty( $smartslider ) && defined( 'NEXTEND_SMARTSLIDER_3' ) ) {
				$slider_stretch = '';
			}
		}
	} else {
		$page_id = get_the_ID();
		$is_wc_shop = vantage_is_woocommerce_active() && is_woocommerce() && is_shop();
		if ( $is_wc_shop ) {
			$page_id = wc_get_page_id( 'shop' );
		}
		if ( is_home() ) {
			$page_id = get_queried_object_id();
		}
		if( ( is_page() || $is_wc_shop || is_home() ) && get_post_meta( $page_id, 'vantage_metaslider_slider', true ) != 'none' && defined( 'METASLIDER_VERSION' ) ) {
			$page_slider = get_post_meta( $page_id, 'vantage_metaslider_slider', true );
			if ( ! empty( $page_slider ) ) {
				$slider = $page_slider;
			}
			$slider_stretch = get_post_meta($page_id, 'vantage_metaslider_slider_stretch', true);
			$smartslider = '';
		}
		if ( ( is_page() || $is_wc_shop ) && get_post_meta( $page_id, 'vantage_smartslider_slider', true) != '' && defined( 'NEXTEND_SMARTSLIDER_3' ) ) {
			$page_slider = get_post_meta( $page_id, 'vantage_smartslider_slider', true );
			if ( ! empty( $page_slider ) ) {
				$smartslider = $page_slider;
			}
			$slider_stretch = false;
		}

	}

	if ( empty( $slider ) && empty( $smartslider ) ) return;

	global $vantage_is_main_slider;
	$vantage_is_main_slider = true;

	?><div id="main-slider" <?php if( $slider_stretch ) echo 'data-stretch="true"' ?>><?php

	if ( $slider == 'demo' ) {
		get_template_part( 'slider/demo' );
	} else {
		if ( substr( $smartslider, 0, 5 ) == 'meta:' && defined( 'NEXTEND_SMARTSLIDER_3' ) ) {
			list( $null, $slider_id ) = explode( ':', $smartslider );
			echo do_shortcode( "[smartslider3 slider=" . intval( $slider_id ) . "]" );
		}

		if ( substr( $slider, 0, 5 ) == 'meta:' && defined( 'METASLIDER_VERSION' ) ) {
			list( $null, $slider_id ) = explode( ':', $slider );
			echo do_shortcode( "[metaslider id=" . intval( $slider_id ) . "]" );
		}
	}

	?></div><?php
	$vantage_is_main_slider = false;
}
```

**Comment by adiraomj** [comment]
@AlexGStapleton thanks. Was helpful. :)

The changes I made: 

- Since the Smart Slider option is the only setting we show by default, I added a demo option to the setting. Similar to what we have on Metaslider. With this the user will able to toggle between the demo slider and the no slider, when both slider plugins are not active.

- Since the new default Smart Slider setting does not come with a stretch slider option, I have added set the  `data-stretch` attribute to true in all cases for the demo slider. What do you guys think?

- @Misplon I had setup the function such that both Metaslider and Smartslider do not display together, with Smartslider having priority over Metaslider. I have changed it.

Please test. Let me know if any further changes are needed. Thanks.

**Comment by Misplon** [comment]
Epic! Thanks Adi. Climbing in shortly. Greg will too for a quick review. I just noticed:

`siteorigin_smartslider_install_link`

We'll need to prefix that:

`vantage_smartslider_install_link`

**Comment by adiraomj** [comment]
Fixed bug #245.
Please test. Thanks

**Comment by Misplon** [comment]
@braamgenis Thanks mate, looking great. 

Is there anyway we can make the stretch setting conditional on selecting either the theme demo slider or a MetaSlider? If we remove the stretch setting when a Smart Slider is selected, it'll remove a lot of potential confusion and explaining.

**Comment by Misplon** [comment]
Going to merge for ease of final changes.

**Pull request merged**
