### PR TITLE
Replaced jetpack's site-logo with WP's custom-logo

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #56

### CODE REVIEW

**Comment by gregpriday** [comment]
Are these both stored in the same place in the database, or does WordPress handle the migration from Jetpack to the core site logo feature?

**Comment by adiraomj** [comment]
From what I read, that does seem to be the case. If you use Jetpack's function, Jetpack will handle the function so as to output custom-logo.

https://make.wordpress.org/core/2016/03/10/custom-logo/

What do you think?

WordPress has also done the same for TwentySixteen.
https://github.com/WordPress/twentysixteen/commit/534708502a1b16aa1d7df32d6865af5df158f105

**Comment by Misplon** [comment]
Code and output looking good. Happy to merge when you are @gregpriday.

**Comment by gregpriday** [comment]
All looked good to me.

**Pull request merged**
