### PR TITLE
Added styling to WooCommerce widgets

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #45 

@Misplon any suggestions to improve it further? :)

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks, @adiraomj.

**Products Widget**
Sorry for not mentioning this before. Going on the requests I've dealt with, I think think most users want the products widget to display products very similarly or the same as the default shop/archive layout. 

This is how it's outputting at the moment:

woocommerce-products-widget

I think most users are looking for a widget output like the shop:

shop

**Comment by Misplon** [comment]
**Product Categories Widget**

Perhaps we could do the following:

Remove the first ul's left margin.
Remove the list style.
Remove the link underline.
But keep the indentation, perhaps just less indentation.

product-categories

**Comment by adiraomj** [comment]
@Misplon the post categories should have the same design as other widget lists.
Can you please check again? I have updated the PR. Here is what I get.

screenshot-localhost 8888 2016-05-31 19-05-19

For the widgets displaying products, I'll make changes to them as you have suggested for the **Products Widget**. We can then review how to proceed with the other widgets.

Lastly. I have not made any changes to the **WooCommerce Layered Nav** and **WooCommerce Layered Nav Filters** widgets. Do you think we should add some styling there?

**Comment by Misplon** [comment]
**WooCommerce Product Categories**
I realise it isn't the default usage but the product categories with lists I highlighted was in Page Builder. I should have mentioned that. The sidebar output is perfect.

_For the widgets displaying products, I'll make changes to them as you have suggested for the Products Widget. We can then review how to proceed with the other widgets._

Yes, perfect.

_Lastly. I have not made any changes to the WooCommerce Layered Nav and WooCommerce Layered Nav Filters widgets. Do you think we should add some styling there?_

Sorry, meant to test those then forgot, will test now and reply.

**Comment by Misplon** [comment]
@adiraomj I just realised that the vertical lists for WooCommerce Products widgets and similar are perfect for the sidebar, however, Page Builder introduces another dimension because users are now using the same widgets but with much more space available and therefore expect a different output. How far do you want to take this? Should we start with the Products widget and do this; leave the styling as is when in `#secondary` but when in Page Builder, change the styling to look like the shop grid. Also, can we look at load time and perhaps make WooCommerce styles conditional on the plugin being activated?

**Comment by Misplon** [comment]
@adiraomj Can you please, have a quick look at this when you have a moment. Thanks :)

**Comment by adiraomj** [comment]
Sure thing. I'll update it in a little while. :)

**Pull request merged**
