### PR TITLE
Added masthead sidebar to be applied above the navigation bar

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #116 

Added new sidebar `sidebar-masthead`.
Checked if sidebar has widgets and added it above the main navigation.

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks, @adiraomj. Initial feedback:

1. Add styling for widget titles.
2. If a Custom Menu widget is added, apply the same styles that would be applied to the Header widget area Custom Menu widget.
3. Align widgets horizontally until a mobile breakpoint. Ensure right margin is applied to each widget except the last until the breakpoint and then removed.

**Comment by Misplon** [comment]
**Point Six:**
@adiraomj We need to remove this area when Logo in Menu is selected. Thanks :)

**Comment by adiraomj** [comment]
@Misplon should we add a setting for the widget title color. We have a setting for widget title color in the footer section.

**Comment by Misplon** [comment]
@adiraomj Sounds good. Let's do it.

**Comment by adiraomj** [comment]
Changes :

- Added styling for widget titles.
- Added styling to custom menu.
- Aligned widgets horizontally until a mobile breakpoint.
- Added description for all sidebars.
- Added setting to change widget title color. ( Placed it under widgets section. Any changes?)
- Applied header padding to masthead sidebar

@Misplon please have a look and let me know if I should make any changes. Thanks :)

**Comment by Misplon** [comment]
Thanks @adiraomj! Getting there. A few more small points:

**Update comment as we're targeting two areas now:**
https://github.com/siteorigin/vantage/pull/144/files#diff-78cd5aa3783a74555c9938a2a81d01c6L289

**Check if sidebar is active first:**
https://github.com/siteorigin/vantage/pull/144/files#diff-b0d8897e4e629cd5072e3b5446520e7dR34

**CSS for header widget count at the moment is mirroring the footer count, in order to get two columns in header you need two in footer:**
https://github.com/siteorigin/vantage/pull/144/files#diff-78cd5aa3783a74555c9938a2a81d01c6R307

**When the header padding is set to the default of 45 I don’t get any padding:**



This is because the setting doesn’t output in default and with the normal header we’re adding padding manually:

```
#masthead .hgroup {
    zoom: 1;
    position: relative;
    padding-top: 45px;
    padding-bottom: 45px;
}
```

but we’re dropping that for the masthead widget area:

```
#masthead .hgroup.masthead-sidebar {
    padding: 0;
}
```

**Comment by adiraomj** [comment]
@Misplon I have made the changes. :)

**Comment by Misplon** [comment]
Looking great! Phew, nearly there. Sorry for missing this, let's add a bottom widget margin after the breakpoint but not for the last widget.

bm

**Comment by Misplon** [comment]
And a [sneaky space](https://github.com/siteorigin/vantage/pull/144/commits/5c88f2350a85a528afd17a96f08a40d9e411ddca#diff-b0d8897e4e629cd5072e3b5446520e7dR34) after the `if`, if you have a moment :)

**Comment by adiraomj** [comment]
Made the changes. Have to get used to the if space ;-)

**Comment by Misplon** [comment]
Such a minor thing these WP style guides, I know :) Thanks, appreciate the effort. (Greg doesn't like that space either).

**Pull request merged**
