### PR TITLE
Vantage: srcset Featured Image

### LINKED ISSUE #226: Blog post featured images are blurry
The featured image used for a post shows up blurry on both archive and single post page

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Fixes #226

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
Can you please send me a copy of the image you're testing against? I ask because that's not what I was getting and the fix did help for me. So, uh, I want to try the image you're using. For reference, here's the image I tried:

https://vgy.me/aPwGeu.png

Before:

``

After:

``

Hm. Actually, are you using Jetpack? I'm pretty sure they forcefully (not that this is a bad thing) change all images to be responsive now.

**Comment by Misplon** [comment]
I was testing using the [Vantage demo](http://demo.siteorigin.com/vantage/blog/) and Jetpack is activated. So that's probably it.

**Comment by Misplon** [comment]
@AlexGStapleton Thanks for the effort mate. Can you check Adi's feedback and let me know your thoughts.

**Comment by AlexGStapleton** [comment]
Really not too sure what to say. I don't get a secret and I do with the fix. Im definitely on the latest version of WP. If you guys are both getting there's really no reason to merge this.

**Comment by Misplon** [comment]
Looks like I do have `srcset` without Jetpack. Cool, let's close for now. Thanks for investigating for us.

**Pull request closed without merging**
