### PR TITLE
fixed logo in menu for .site-title

### PR DESCRIPTION
**Pull request by adiraomj**
Fixed issue #95 

@Misplon I have not added any hover styling. Please let me know if it's needed. Thanks.

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj Looking great.

The challenge is that the logo size is different so our default at Theme Design > Fonts > Site Title Size doesn't make sense anymore. I don't suppose there is a way to conditionally change the default based on the masthead layout selection?

**Comment by adiraomj** [comment]
Not that I know. Any ideas as to how we solve this? @gregpriday

**Comment by gregpriday** [comment]
Tough one, because the Site Title Size default would only apply before the user saves anything in the customizer - which they'd need to do to change the masthead layout anyway.

One solution here might be to map the one to the other. So say that when the user has logo in menu selected, then the site title is actually equal to `site_title * 0.5` for example. You'd just need to pick a value that makes sense there.

Any thoughts on that solution? It would just mean using a callback for this particular customizer setting.

**Comment by Misplon** [comment]
@gregpriday A linked size would be the best option I think. @adiraomj Can you have a look at this? Try making the site title some percentage of the default header site title size. That way the setting would still be applicable to the site title when Logo in Menu is being used. I can document the settings ratio.

**Comment by Misplon** [comment]
@adiraomj When you have moment, could please, try this out for us?

**Comment by adiraomj** [comment]
I'll get it done tonight :)

**Comment by Misplon** [comment]
@adiraomj Any chance you've been able to check this one out? Thanks :)

**Comment by adiraomj** [comment]
@gregpriday need some help with this one. This is what I have done: 

The setting
```
'site_title_size' => array(
	'type' => 'measurement',
	'title' => __('Site Title Size', 'vantage'),
	'default' => 36,
	'unit' => 'px',
	'property' => array('font-size'),
	'callback' => 'vantage_customizer_callback_site_title_size',
),
```

The callback
```
function vantage_customizer_callback_site_title_size($builder, $val, $setting){
	$mh_layout = siteorigin_setting( 'layout_masthead' );
	if ( $mh_layout == 'logo-in-menu' ) {
		$builder->add_css('#masthead .hgroup h1, #masthead.masthead-logo-in-menu .logo > h1', 'font-size', $val*0.6 . 'px');
	} else {
		$builder->add_css('#masthead .hgroup h1, #masthead.masthead-logo-in-menu .logo > h1', 'font-size', $val . 'px');
	}
	return $builder;
}
```

Any advice? Thanks

**Comment by gregpriday** [comment]
So I think  you won't need the `property` attribute in the `site_title_size` array, but besides that, it looks good. Is it working?

**Comment by adiraomj** [comment]
Yup. Does what it's expected to. Thanks. I'll update the PR now. :)

**Comment by Misplon** [comment]
Yes!

**Pull request merged**
